# Generated by Django 5.1.2 on 2024-10-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_price_alter_materialhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
