# Generated by Django 5.1.2 on 2024-10-23 18:43

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryitem_date_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
