# Generated by Django 5.1.2 on 2024-10-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
