# Generated by Django 5.1.2 on 2024-11-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_location_inventoryitem_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
